### ISSUE TITLE
how do I upload my own face images

### ISSUE THREAD

**Issue by heaversm** [EnoxSoftware/FaceMaskExample#1]
Hi - I purchased dlib face detector and openCV from Enox but the face mask example doesn't provide any documentation on how to use my own images as masks within the WebcamTextureFaceMaskExample scene. Can you point me to some documentation on how to do this? This is the reason I purchased all the software. Thanks!

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

You can add new mask data by the following procedure. When "Is Dynamic Mode" is enabled, the landmark point of the face is automatically specified.
![add_new_mask_data](https://user-images.githubusercontent.com/7920392/47281328-7c211400-d615-11e8-90a7-c017e7d43522.png)

**Comment by heaversm** [comment]
Gives the error `image==null`.

<img width="340" alt="screen shot 2018-10-22 at 7 35 01 am" src="https://user-images.githubusercontent.com/520541/47298696-49532d80-d5cd-11e8-89f2-280f046f6a51.png">

**Comment by heaversm** [comment]
Says `maskData == null` and does not display an image, even though I have a texture2D with the exact settings of the other face masks. 

<img width="1051" alt="screen shot 2018-10-22 at 7 44 29 am" src="https://user-images.githubusercontent.com/520541/47299174-76541000-d5ce-11e8-8923-b2d26ef66dad.png">

<img width="341" alt="screen shot 2018-10-22 at 7 45 51 am" src="https://user-images.githubusercontent.com/520541/47299196-8966e000-d5ce-11e8-852a-ac6f252fab73.png">

**Comment by heaversm** [comment]
Also - did some debugging. For the new added prefab:

```
FaceMaskData maskData = faceMaskDatas[faceMaskDataIndex];
            faceMaskDataIndex = (faceMaskDataIndex < faceMaskDatas.Count - 1) ? faceMaskDataIndex + 1 : 0;
            Debug.Log(maskData);
```

`maskData` is coming through as null (though `faceMaskDataIndex` is correct). Is there something explicit I have to do to add it to the `faceMaskDatas` array other than put it as a child of the FaceMaskData game object?

<img width="122" alt="screen shot 2018-10-22 at 10 54 32 am" src="https://user-images.githubusercontent.com/520541/47309294-e1aadb80-d5e8-11e8-9bee-ac2047bc7d7f.png">

I noticed that there is a `OnWebCamTextureToMatHelperDisposed` log, with a progress bar that never fills up. In play mode, it says `bake paused in play mode`. Is this supposed to run in order for the software to work?

<img width="1740" alt="screen shot 2018-10-22 at 10 52 06 am" src="https://user-images.githubusercontent.com/520541/47309348-069f4e80-d5e9-11e8-9a4b-541cbe83006e.png">

**Comment by heaversm** [comment]
Ah, figured it out. There's a list declared on the `Quad` game object. Just had to add it to that. Thanks for your help.

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.
It seems that an additional procedure is required.

Please add "New MaskData" to "FaceMaskDatas".
<img width="1221" alt="facemask_example" src="https://user-images.githubusercontent.com/7920392/47360969-c4baf900-d70b-11e8-99cf-2097964380ec.png">
