### ISSUE TITLE
All of the sudden getting lots of errors when using this.

### ISSUE THREAD

**Issue by heaversm** [EnoxSoftware/FaceMaskExample#2]
Process:

* Start a new project
* Import OpenCV for Unity
* Follow steps in OpenCV for Unity Readme
* Test OpenCVForUnityExample - works fine
* Import FaceTrackerExample
* Open FaceTrackerARExample Scene and add to Build Settings
* Push Play in Editor.
*Get many erros such as:

<img width="1281" alt="screen shot 2019-01-09 at 5 24 16 pm" src="https://user-images.githubusercontent.com/520541/50939964-d91db080-1433-11e9-94a0-d20890148574.png">
<img width="1117" alt="screen shot 2019-01-09 at 5 24 32 pm" src="https://user-images.githubusercontent.com/520541/50939965-d91db080-1433-11e9-868c-071fdecbcebc.png">
<img width="970" alt="screen shot 2019-01-09 at 5 28 02 pm" src="https://user-images.githubusercontent.com/520541/50940055-429dbf00-1434-11e9-8f2e-4f001e25c754.png">

**Comment by heaversm** [comment]
Also - noticed it says it requires OpenCVforUnity2.3.3, but latest available version according to Asset Store release notes is 2.3.2.

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

OpenCV for Unity v2.3.3 is in pending review status.
I asked Unity Support about the review. I got a reply that the Asset Review
Team is now in the holiday season so it will take some more time to finish
the review.

Until OpenCVForUnity 2.3.3 is published in AssetStore, you can download
examples of older versions from the following DL link.


DlibFaceLandmarkDetector_v1.2.5_to_v1.2.4_Patch.unitypackage
https://www.dropbox.com/s/s4ggi4ps4...ctor_v1.2.5_to_v1.2.4_Patch.unitypackage?dl=0
By importing this unitypackage you can downgrade DlibFaceLandmarkDetector v1.2.5 to DlibFaceLandmarkDetector v1.2.4. Please import DlibFaceLandmarkDetector v1.2.5 from AssetStore and then import this patch. FaceSwapperExample 1.0.7, FaceMaskExample 1.0.6 and CVVTuberExample 1.0.1 require DlibFaceLandmarkDetector 1.2.4.


CVVTuberExample1.0.1
https://www.dropbox.com/s/tccnr216bwq1xiq/CVVTuberExample1.0.1.unitypackage?dl=0

DlibFaceLandmarkDetectorPlayMakerActions1.0.2
https://www.dropbox.com/s/jkwsk6c2p...tectorPlayMakerActions1.0.2.unitypackage?dl=0

OpenCVForUnityPlayMakerActions1.0.5
https://www.dropbox.com/s/x4xo907pnda7chh/OpenCVForUnityPlayMakerActions1.0.5.unitypackage?dl=0

FaceMaskExample1.0.6
https://www.dropbox.com/s/aly2gtf5vmji6x6/FaceMaskExample1.0.6.unitypackage?dl=0

FaceSwapperExample1.0.7
https://www.dropbox.com/s/6gwa0v8eunqjnv5/FaceSwapperExample1.0.7.unitypackage?dl=0

FaceTrackerExample1.1.8
https://www.dropbox.com/s/u2cx1nlkddz8lnn/FaceTrackerExample1.1.8.unitypackage?dl=0

MarkerBasedARExample1.2.1
https://www.dropbox.com/s/u2rfto39ohu18ja/MarkerBasedARExample1.2.1.unitypackage?dl=0

MarkerLessARExample1.0.4
https://www.dropbox.com/s/rpovz53y3hhhlgj/MarkerLessARExample1.0.4.unitypackage?dl=0

RealTimeFaceRecognitionExample1.0.4
https://www.dropbox.com/s/rjot3qaih580xyp/RealTimeFaceRecognitionExample1.0.4.unitypackage?dl=0


Regerds,
EnoxSoftware

**Comment by heaversm** [comment]
Thank you!
